#! /bin/sh
# Accepts an optional volume pathname as returned by trivialfs_volume and a
# file name as arguments, and (if successful only) writes the start index,
# byte size and volume pathname as a single line to standard output, separated
# by a single ASCII SPACE. If only a single argument is provided, it reads the
# volume path name from standard input.
#
# trivialfs_file version 2016.175
#
# Copyright (c) 2014-2016 Guenther Brunthaler. All rights reserved.
# 
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
trap 'echo "$0 Failed!" >& 2' 0
target_path=
volume_path=
while getopts "" opt
do
	case $opt in
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`
if test $# -ge 2
then
	volume_path=$1; shift
else
	IFS= read -r volume_path
fi
test $# != 0 && { target_path=$1; shift; }
test $# = 0
test -n "$volume_path"
test -n "$target_path"; test x"$target_path" = x"${target_path#/}"

export LC_COLLATE=C # Just in case "case" makes use of it in comparisons.
while IFS= read -r line
do
	case $line in
		"@"*"=$target_path")
			start=${line%%"="*}; size=${start#*"+"}
			start=${start#"@"}; start=${start%"+"*}
			echo "$start $size $volume_path"
			trap - 0; exit
			;;
		*"="*) ;;
		*) break
	esac
done < "$volume_path"
trap - 0; false
